[build]
  publish = "public"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/:shortId"
  to = "/espectador.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
